# Generated by Django 4.2.7 on 2023-11-02 14:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('photos', '0002_category_handbag_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='handbag',
            name='bio',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='handbag',
            name='price',
            field=models.TextField(null=True),
        ),
    ]
