# Generated by Django 4.2.7 on 2023-11-04 15:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('photos', '0003_handbag_bio_handbag_price'),
    ]

    operations = [
        migrations.RenameField(
            model_name='handbag',
            old_name='image',
            new_name='image1',
        ),
        migrations.AddField(
            model_name='handbag',
            name='image2',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
        migrations.AddField(
            model_name='handbag',
            name='image3',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
        migrations.AddField(
            model_name='handbag',
            name='image4',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
        migrations.AddField(
            model_name='handbag',
            name='image5',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
    ]
