# Generated by Django 4.2.7 on 2023-11-04 15:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('photos', '0004_rename_image_handbag_image1_handbag_image2_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='handbag',
            old_name='image1',
            new_name='image',
        ),
        migrations.RemoveField(
            model_name='handbag',
            name='image2',
        ),
        migrations.RemoveField(
            model_name='handbag',
            name='image3',
        ),
        migrations.RemoveField(
            model_name='handbag',
            name='image4',
        ),
        migrations.RemoveField(
            model_name='handbag',
            name='image5',
        ),
    ]
