# Generated by Django 4.2.7 on 2023-11-04 16:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('photos', '0006_rename_image_handbag_image1_handbag_image2_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='handbag',
            name='image1',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
    ]
